mask

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -74,17 +74,22 @@ jobs:
           BOTTLE_ARCH=$(echo "$BOTTLE_FILE" | grep -oE '(arm64_tahoe|tahoe)\.bottle' | cut -d'.' -f1)
           brew tap-new local/math
           TAP_DIR=$(brew --repository local/math)
+          SRC_TAP_DIR=$(brew --repository cammgh/math 2>/dev/null || echo "")
           cp ./Formula/gcl27.rb "$TAP_DIR/Formula/gcl27.rb"
           BOTTLE_SHA=$(shasum -a 256 $BOTTLE_FILE | awk '{print $1}')
           cp $BOTTLE_FILE $TAP_DIR/$(echo $BOTTLE_FILE | sed 's,--,-,1')
-          cp Formula/* $TAP_DIR/Formula/
-          sed -i '' 's@depends_on "cammgh/math/gcl27"@depends_on "local/math/gcl27"@g' "$TAP_DIR/Formula/hol88-gcl.rb"
+          #cp Formula/* $TAP_DIR/Formula/
+          #sed -i '' 's@depends_on "cammgh/math/gcl27"@depends_on "local/math/gcl27"@g' "$TAP_DIR/Formula/hol88-gcl.rb"
           cd $TAP_DIR
-          cp Formula/gcl27.rb Formula/gcl27.rb.old
+          #cp Formula/gcl27.rb Formula/gcl27.rb.old
           sed -i '' "s@root_url .*@root_url \"file://$TAP_DIR\"@g" Formula/gcl27.rb
           sed -i '' "s/# sha256 cellar.*/sha256 cellar: :any, $BOTTLE_ARCH: \"${BOTTLE_SHA}\"/g" Formula/gcl27.rb
-          brew untap cammgh/math || true
+          #brew untap cammgh/math || true
+          if [ -d "$SRC_TAP_DIR/Formula" ]; then mv "$SRC_TAP_DIR/Formula" "$SRC_TAP_DIR/Formula.bak"; fi
+          if [ -d "$SRC_TAP_DIR/HomebrewFormula" ]; then mv "$SRC_TAP_DIR/HomebrewFormula" "$SRC_TAP_DIR/HomebrewFormula.bak"; fi
           brew install --formula "$TAP_DIR/Formula/gcl27.rb"
+          if [ -d "$SRC_TAP_DIR/Formula.bak" ]; then mv "$SRC_TAP_DIR/Formula.bak" "$SRC_TAP_DIR/Formula"; fi
+          if [ -d "$SRC_TAP_DIR/HomebrewFormula.bak" ]; then mv "$SRC_TAP_DIR/HomebrewFormula.bak" "$SRC_TAP_DIR/HomebrewFormula"; fi
           #brew tap-new cammgh/math
           #NEW_TAP_PATH=$(brew --repository cammgh/math)
           #rm -rf "$NEW_TAP_PATH/Formula" "$NEW_TAP_PATH/HomebrewFormula"
@@ -131,9 +136,9 @@ jobs:
       - name: Build HOL88
         if: github.ref_name == 'hol88'
         run: |
-          brew audit --formula "local/math/hol88-gcl" --online || echo "Audit failure, continuing"
-          brew install --formula --verbose --build-from-source "local/math/hol88-gcl"
-          brew test "local/math/hol88-gcl"
+          brew audit --formula "cammgh/math/hol88-gcl" --online || echo "Audit failure, continuing"
+          brew install --formula --verbose --build-from-source "cammgh/math/hol88-gcl"
+          brew test "cammgh/math/hol88-gcl"
 
       - name: Build AXIOM
         if: github.ref_name == 'axiom'
